portal/portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
]

portal/website/urls.py
from django.contrib import admin
from django.urls import path, include
from website.views import main_view, car_view

urlpatterns = [
    path('', main_view, name = "main"),
    path('<int:pk>', car_view, name = "car")
]

portal/car/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
# Create your models here.

class CarMain(models.Model):
    make = models.CharField(max_length=16)
    model = models.CharField(max_length=32)

class CarDetail(models.Model):
    CAR_COLORS = [
        ("RED", "Red"),
        ("BLU", "Blue"),
        ("YEL", "Yellow"),
        ("BLA", "Black"),
        ("WHI", "White")
    ]
    CAR_FUELS = [
        ("DIE", "Diesel"),
        ("PET", "Petrol"),
        ("HYB", "Hybrid"),
        ("LPG", "LPG"),
        ("ELE", "Electric"),
    ]
    production_date = models.DateField()
    color = models.CharField(max_length=3, choices=CAR_COLORS)
    seats = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(9)])
    fuel = models.CharField(max_length=3, choices=CAR_FUELS)
    power = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(0.00)])

class Car(models.Model):
    main = models.ForeignKey(CarMain, on_delete=models.CASCADE)
    detail = models.OneToOneField(CarDetail, on_delete=models.PROTECT)

    def delete(self):
        super(Car, self).delete()
        self.detail.delete()

    def __str__(self):
        return f"{self.main.make} {self.main.model}"

portal/website/models.py
from django.db import models

# Create your models here.

portal/car/forms.py
from .models import Car, CarDetail, CarMain
from django.forms import ModelForm, DateInput
from django import forms
from django.core.validators import MinValueValidator

class CarForm(ModelForm):
    class Meta:
        model = Car
        fields = ['main', 'detail']


class CarDetailForm(ModelForm):
    production_date_start = forms.DateField(widget=DateInput(
                format=('%d/%m/%Y'),
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Select a date',
                    'type': 'date',}
            ))
    production_date_end = forms.DateField(widget=DateInput(
                format=('%d/%m/%Y'),
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Select a date',
                    'type': 'date',}
            ))
    power_min = forms.IntegerField(min_value=0)
    power_max = forms.IntegerField(min_value=0)
    price_min = forms.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(0.00)])
    price_max = forms.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(0.00)])
    class Meta:
        model = CarDetail
        exclude = ('car', 'power', 'production_date', 'price')


    def __init__(self, *args, **kwargs):
        super(CarDetailForm, self).__init__(*args, **kwargs)
        self.fields['color'].required = False
        self.fields['seats'].required = False
        self.fields['fuel'].required = False
        self.fields['production_date_end'].required = False
        self.fields['production_date_start'].required = False
        self.fields['power_min'].required = False
        self.fields['power_max'].required = False
        self.fields['price_min'].required = False
        self.fields['price_max'].required = False


class CarMainForm(ModelForm):
    class Meta:
        model = CarMain
        exclude = ('car', )

    def __init__(self, *args, **kwargs):
        super(CarMainForm, self).__init__(*args, **kwargs)
        self.fields['model'].required = False
        self.fields['make'].required = False

portal/website/views.py
from django.shortcuts import render

# Create your views here.
from car.forms import CarForm, CarDetailForm, CarMainForm
from car.models import Car, CarDetail, CarMain


def main_view(request):
    context = {}
    template = "main.html"
    if request.method == 'GET':
        car_detail_form = CarDetailForm(prefix='detail')
        car_main_form = CarMainForm(prefix='main')
        context["car_detail_form"] = car_detail_form
        context["car_main_form"] = car_main_form
        return render(request, template, context)
    if request.method == "POST":
        cars = Car.objects.select_related("main").select_related("detail").all()
        car_detail_form = CarDetailForm(request.POST, prefix='detail')
        car_main_form = CarMainForm(request.POST, prefix='main')
        if car_detail_form.is_valid() and car_main_form.is_valid():
            make = car_main_form.cleaned_data['make']
            if make:
                cars = cars.filter(main__make=make)

            model = car_main_form.cleaned_data['model']
            if model:
                cars = cars.filter(main__model=model)

            #detail
            color = car_detail_form.cleaned_data['color']
            if color:
                cars = cars.filter(detail__color=color)

            seats = car_detail_form.cleaned_data['seats']
            if seats:
                cars = cars.filter(detail__seats=seats)

            fuel = car_detail_form.cleaned_data['fuel']
            if fuel:
                cars = cars.filter(detail__fuel=fuel)


            power_min = car_detail_form.cleaned_data['power_min']
            power_max = car_detail_form.cleaned_data['power_max']
            if power_min:
                cars = cars.filter(detail__power__gte=power_min)
            if power_max:
                cars = cars.filter(detail__power__lte=power_max)

            price_min = car_detail_form.cleaned_data['price_min']
            price_max = car_detail_form.cleaned_data['price_max']
            if price_min:
                cars = cars.filter(detail__price__gte=price_min)
            if price_max:
                cars = cars.filter(detail__price__lte=price_max)


            production_date_start = car_detail_form.cleaned_data['production_date_start']
            production_date_end = car_detail_form.cleaned_data['production_date_end']
            if production_date_start:
                cars = cars.filter(detail__production_date__gte=production_date_start)
            if production_date_end:
                cars = cars.filter(detail__production_date__lte=production_date_end)

        context['cars'] = cars
        print(cars)
        context["car_detail_form"] = car_detail_form
        context["car_main_form"] = car_main_form
        return render(request, template, context)


def car_view(request, pk):
    template="car.html"
    context={}
    if request.method == "GET":
        car = Car.objects.get(id=pk)
        context['car'] = car
        return render(request, template, context)

portal/website/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Portal Samochodowy</title>
</head>

<style>

    td, th {
        text-align:left;
        padding: 5px;
    }
</style>

<body>
{% block content %}{% endblock content %}
</body>
</html>

portal/website/templates/car.html
{% extends "base.html" %}

{% block content %}
<div><a href="{% url 'main' %}">BACK</a></div>
<table>
    <tr>
        <th>Make</th>
        <td>{{ car.main.make }}</td>
    </tr>
    <tr>
        <th>Model</th>
        <td>{{ car.main.model }}</td>
    </tr>
    <tr>
        <th>Color</th>
        <td>{{ car.detail.get_color_display }}</td>
    </tr>
    <tr>
        <th>No.seats</th>
        <td>{{ car.detail.seats }}</td>
    </tr>
    <tr>
        <th>Fuel</th>
        <td>{{ car.detail.get_fuel_display }}</td>
    </tr>
    <tr>
        <th>Power</th>
        <td>{{ car.detail.power }}</td>
    </tr>
    <tr>
        <th>Production date</th>
        <td>{{ car.detail.production_date }}</td>
    </tr>
    <tr>
        <th>PRICE</th>
        <td>${{ car.detail.price }}</td>
    </tr>
</table>
{% endblock content %}

portal/website/templates/main.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ car_detail_form }}
    {{ car_main_form }}
    <input type="submit" value="Search">
</form>
<table>
    <tr>
        <th>Make</th>
        <th>Model</th>
        <th>Color</th>
        <th>Seats</th>
        <th>Fuel</th>
        <th>Power</th>
        <th>Production Date</th>
        <th>Price</th>
    </tr>
{% for car in cars %}
    <tr>
                <td>{{ car.main.make }}</td>
                <td>{{ car.main.model }}</td>
                <td>{{ car.detail.get_color_display }}</td>
                <td>{{ car.detail.seats }}</td>
                <td>{{ car.detail.get_fuel_display }}</td>
                <td>{{ car.detail.power }}</td>
                <td>{{ car.detail.production_date }}</td>
                <td>${{ car.detail.price }}</td>
                <td><a href="{% url 'car' car.id %}"> GO </a></td>

    </tr>

{% endfor %}
</table>
{% endblock content %}